[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable scanning only for frontend safe keys
  SECRETS_SCAN_OMIT_KEYS = "VITE_BACKEND_URL,VITE_GOOGLE_MAPS_API_KEY,VITE_GOOGLE_CLIENT_ID,VITE_RAZORPAY_KEY_ID"
