export const properties = [
    {
      id: 1,
      name: "Silva Heritage, South Goa Pet Pool Villa",
      location: "Benaulim, India",
      beds: 5,
      baths: 5,
      guests: 10,
      price: 29999,
      rating: 5.0,
      image: "/api/placeholder/400/250",
    },
    {
      id: 2,
      name: "15 BHK Hills Estate, Pawna Lake Pet Pool Villa",
      location: "Pawna Lake, India",
      beds: 15,
      baths: 15,
      guests: 50,
      price: 19999,
      rating: 4.7,
      image: "/api/placeholder/400/250",
    },
    {
      id: 3,
      name: "Villa Vanessa, North Goa Pet Pool Villa",
      location: "Siolim, India",
      beds: 5,
      baths: 5,
      guests: 12,
      price: 9999,
      rating: 4.7,
      image: "/api/placeholder/400/250",
    },
    {
      id: 4,
      name: "Sands & Streams 4BHK Pet Pool Villa",
      location: "Arpora, India",
      beds: 4,
      baths: 4,
      guests: 12,
      price: 21999,
      rating: 4.5,
      image: "/api/placeholder/400/250",
    },
    {
      id: 5,
      name: "Sands & Streams 4BHK Pet Pool Villa",
      location: "Arpora, India",
      beds: 4,
      baths: 4,
      guests: 12,
      price: 28999,
      rating: 4.5,
      image: "/api/placeholder/400/250",
    },
    {
      id: 6,
      name: "Sands & Streams 4BHK Pet Pool Villa",
      location: "Arpora, India",
      beds: 4,
      baths: 4,
      guests: 12,
      price: 19999,
      rating: 4.5,
      image: "/api/placeholder/400/250",
    },
    {
      id: 7,
      name: "Sands & Streams 4BHK Pet Pool Villa",
      location: "Arpora, India",
      beds: 4,
      baths: 4,
      guests: 12,
      price: 8999,
      rating: 4.5,
      image: "/api/placeholder/400/250",
    },
    {
      id: 8,
      name: "Sands & Streams 4BHK Pet Pool Villa",
      location: "Arpora, India",
      beds: 4,
      baths: 4,
      guests: 12,
      price: 39999,
      rating: 4.5,
      image: "/api/placeholder/400/250",
    },
  ];
  